log:
  stdout: true
  level: "${LOG_LEVEL}"

persistence:
  defaultStore: cass-default
  visibilityStore: cass-visibility
  numHistoryShards: ${NUM_HISTORY_SHARDS}
  datastores:
    cass-default:
      cassandra:
        hosts: "${CASSANDRA_SEEDS}"
        keyspace: "${KEYSPACE}"
        consistency: "${CASSANDRA_CONSISTENCY}"
    cass-visibility:
      cassandra:
        hosts: "${CASSANDRA_SEEDS}"
        keyspace: "${VISIBILITY_KEYSPACE}"
        consistency: "${CASSANDRA_CONSISTENCY}"

ringpop:
  name: cadence
  bootstrapMode: hosts
  bootstrapHosts: ${RINGPOP_SEEDS_JSON_ARRAY}
  maxJoinDuration: 30s

services:
  frontend:
    rpc:
      port: 7933
      bindOnLocalHost: ${BIND_ON_LOCALHOST}
      bindOnAllInterfaces: ${BIND_ON_ALL_INTERFACES}
    metrics:
      statsd:
        hostPort: "${STATSD_ENDPOINT}"
        prefix: "cadence-frontend"

  matching:
    rpc:
      port: 7935
      bindOnLocalHost: ${BIND_ON_LOCALHOST}
      bindOnAllInterfaces: ${BIND_ON_ALL_INTERFACES}
    metrics:
      statsd:
        hostPort: "${STATSD_ENDPOINT}"
        prefix: "cadence-matching"

  history:
    rpc:
      port: 7934
      bindOnLocalHost: ${BIND_ON_LOCALHOST}
      bindOnAllInterfaces: ${BIND_ON_ALL_INTERFACES}
    metrics:
      statsd:
        hostPort: "${STATSD_ENDPOINT}"
        prefix: "cadence-history"

  worker:
    rpc:
      port: 7939
      bindOnLocalHost: ${BIND_ON_LOCALHOST}
      bindOnAllInterfaces: ${BIND_ON_ALL_INTERFACES}
    metrics:
      statsd:
        hostPort: "${STATSD_ENDPOINT}"
        prefix: "cadence-worker"

clustersInfo:
  enableGlobalDomain: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInitialFailoverVersion:
    active: 0
    standby: 1
